<?php
return [
    'Zend\ServiceManager\Di',
    'Zend\Session',
    'Zend\Mvc\Plugin\Prg',
    'Zend\Mvc\Plugin\Identity',
    'Zend\Mvc\Plugin\FlashMessenger',
    'Zend\Mvc\Plugin\FilePrg',
    'Zend\Mvc\I18n',
    'Zend\Mvc\Console',
    'Zend\Log',
    'Zend\Form',
    'Zend\Cache',
    'Zend\Router',
    'Zend\Navigation',
    'Zend\I18n',
    'Zend\Validator',
    'ZendDeveloperTools',
    'Application',
    'ZendBricks\BricksCommon',
    'ZendBricks\BricksUser',
    'User'
];
