<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('BricksExampleApplication')->setSeparator(' - ')->setAutoEscape(false);
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'));
        echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.js'));
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>">Example Application</a>
            </div>
            <div class="collapse navbar-collapse">
                <?php // echo $this->navigation('navigation')->menu()->setMaxDepth(0)->setPartial('layout/navigation')->setUlClass('nav navbar-nav') ?>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
                </ul>
            </div>
        </nav>
        <div class="col-xs-12">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2016 - <?php echo date('Y') ?> by ZendBricks.</p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
