<?php /* @var $container \Zend\Navigation\Navigation */ ?>
<ul class="<?= $this->navigation($container)->menu()->getUlClass() ?>">
    <?php /* @var $page \Zend\Navigation\Page\Mvc */
    foreach ($container as $page):
        // simple nav item
        if (!$page->hasPages()):
            if (!$this->navigation()->accept($page)) continue; ?>
        <li<?= ($page->isActive()) ? ' class="active"' : '' ?>>
            <a 
                class="nav-header" 
                href="<?= $page->getHref() ?>"
                <?= ($page->getTarget()) ? ' target="' . $page->getTarget() . '"' : '' ?>
                >
                <?php if (!empty($page->get("icon"))): ?>
                    <span class="<?= $page->get("icon") ?>"></span>
                <?php endif ?>
                <?= $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())) ?>
            </a>
        </li>
        <?php
        // dropdown nav item
        else:
            //look for active or accessable items
            $access = $active = false;
            /* @var $subNav \Zend\Navigation\Page\Mvc */
            $page->valid();
            foreach ($page->getPages() as $subNav) {
                if ($this->navigation()->accept($subNav)) {
                    $access = true;
                    if ($active) break;
                }
                if ($subNav->isActive()) {
                    $active = true;
                    if ($access) break;
                }
            }
            if ($access): ?>
                <li class="dropdown<?= ($active) ? ' active' : '' ?>">
                    <a class="nav-header dropdown-toggle" data-toggle="dropdown" href="#">
                        <?php if (!empty($page->get("icon"))): ?>
                            <span class="<?= $page->get("icon") ?>"></span>
                        <?php endif ?>
                        <?= $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())) ?>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <?php
                        $subNavs = new \Zend\Navigation\Navigation($page->getPages());
                        foreach ($subNavs as $subNav):
                            if (!$this->navigation()->accept($subNav)) continue; ?>
                            <li<?= ($subNav->isActive()) ? ' class="active"' : '' ?>>
                                <a 
                                    href="<?= $subNav->getHref() ?>"
                                    <?= ($subNav->getTarget()) ? ' target="' . $subNav->getTarget() . '"' : '' ?>
                                    >
                                    
                                    <?php if (!empty($page->get("icon"))): ?>
                                        <span class="<?= $page->get("icon") ?>"></span>
                                    <?php endif ?>
                                    <?= $this->escapeHtml($this->translate($subNav->getLabel(), $this->navigation($container)->getTranslatorTextDomain())) ?>
                                </a>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </li>   
            <?php endif ?>
        <?php endif ?>
    <?php endforeach ?>
</ul>