<div class="jumbotron">
    <h1>Welcome to ZendBricks</h1>

    <p>
        The intention of BricksExampleApplication is to provide you a simple application which is using all Bricks components.
    </p>
    <p>
        Explore the features of Bricks by navigating through this small website and then check the related code and configuration.
    </p>
    <p>
        Feel free to use this application to initialize your own application or copy some code or configuration snippets to your existing project!
    </p>
    <p>
        Your feedback is welcome at <a href="https://github.com/zend-bricks/BricksExampleApplication" target="_blank">github.com</a>.
    </p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Used Bricks components</h3>
            </div>
            <div class="panel-body">
                <p>
                    This is a list of all Bricks used in this application:
                </p>
                <ul>
                    <li></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Bricks are very flexible!</h3>
            </div>
            <div class="panel-body">
                <p>
                    There are a lot of specialized modules for a specific Framework using a specific database or ORM/ODM.
                </p>
                <p>
                    Bricks are built based on Zend Framework components but you may get them working also in other frameworks.
                </p>
                <p>
                    Bricks doesn't provide any database implementation. You have to write an Api class for each Brick which implements the specific interface and provides the specific database implementations.
                    This sounds like a lot of work but will give you the flexibility to use any combination of databases and abstraction libraries you want. You also can use a REST Api or what ever you want instead of a database!
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Style & templates</h3>
            </div>
            <div class="panel-body">
                <p>
                    You will be able to use Bricks with your own templates but there will be basic templates you can use as well.
                    More info about this soon...
                </p>
            </div>
        </div>
    </div>
</div>
